matrix:
  include:
    - name: x86_64-pc-linux-gnu
      os: linux
      env: TARGET=x86_64-pc-linux-gnu
      services:
        - docker
    - name: powerpc-unknown-linux-gnu
      os: linux
      dist: xenial
      env: TARGET=powerpc-unknown-linux-gnu
    - name: osx
      os: osx
      env: TARGET=osx

addons:
  apt:
    packages:
      - sshpass
      - qemu
      - qemu-system-ppc
      - openssh-client
      - openbios-ppc

before_install:
  - BUILD_IMAGE=true ci/travis.sh

script:
  - sandbox_run pwd
  - touch hello
  - sandbox_run test -e hello

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
