language: minimal

services:
  - docker

env:
  matrix:
    - TARGET=powerpc-unknown-linux-gnu

before_install:
  - IMAGE_NAME=hortaebi/port-of-hmmer:$TARGET
  - (cd $TARGET && docker build -t $IMAGE_NAME .)
  - docker run -dit -v $TRAVIS_BUILD_DIR:/hostdir --name $TARGET $IMAGE_NAME
  - |
    until [ "`docker inspect -f {{.State.Health.Status}} $TARGET`"=="healthy" ]
    do
      sleep 15;
      echo "Waiting for docker service to finish startup..."
    done;

script:
  - docker exec -t $TARGET ssh_run pwd
  - docker exec -t $TARGET ssh_run ls

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
