language: minimal

services:
  - docker

matrix:
  include:
    - env: TARGET=x86_64-pc-linux-gnu
      name: x86_64-pc-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
      name: powerpc-unknown-linux-gnu
    - os: osx
      env: TARGET=osx
      name: osx

addons:
  apt:
    packages:
      - sshpass
      - qemu
      - qemu-system-ppc
      - openssh-client

before_install:
  - BUILD_IMAGE=true ci/travis.sh

script:
  - sandbox_run pwd

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
