language: minimal

services:
  - docker

matrix:
  include:
    - env: TARGET=x86_64-pc-linux-gnu
      name: x86_64-pc-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
      name: powerpc-unknown-linux-gnu

before_install:
  - IMAGE_NAME=hortaebi/port-of-hmmer:$TARGET
  - (cd $TARGET && docker build -t $IMAGE_NAME .)
  - docker run -dit -v $TRAVIS_BUILD_DIR:/hostdir --name $TARGET $IMAGE_NAME
  - |
    until [ "`docker inspect -f {{.State.Health.Status}} $TARGET`" == "healthy" ]
    do
      sleep 15;
      echo "Waiting for docker service to finish startup..."
    done;

script:
  - sandbox_run pwd
  - sandbox_run ls

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
