language: minimal

services:
  - docker

env:
  matrix:
    - TARGET=powerpc-unknown-linux-gnu

before_install:
- (cd $TARGET && docker build -t $TARGET .)
- touch $TARGET/hello
- docker run -v $TRAVIS_BUILD_DIR:/hostdir $TARGET /bin/bash -c "test -e /hostdir/$TARGET/hello"

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
