language: minimal

services:
  - docker

env:
  matrix:
    - TARGET=powerpc-unknown-linux-gnu

before_install:
- (cd $TARGET && docker build -t $TARGET .)
- docker run -d -v $TRAVIS_BUILD_DIR:/hostdir --name $TARGET -t $TARGET
- docker exec -t $TARGET ./setup.sh

script:
- touch $TARGET/hello
- docker exec -t $TARGET test -e $TARGET/hello
- rm $TARGET/hello

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
