language: minimal

env:
  global:
    - PATH=$HOME/bin:$PATH

matrix:
  include:
    - name: x86_64-pc-linux-gnu
      os: linux
      env: TARGET=x86_64-pc-linux-gnu
    - name: powerpc-unknown-linux-gnu
      os: linux
      dist: xenial
      env: TARGET=powerpc-unknown-linux-gnu
    - name: osx
      os: osx
      env: TARGET=osx

addons:
  apt:
    packages:
      - openbios-ppc
      - openssh-client
      - qemu
      - qemu-system-ppc
      - sshpass

before_install:
  - ci/travis.sh

script:
  - touch hello
  - sandbox_run test -e hello
  - sandbox_run rm hello
  - sandbox_run mkdir hello
  - test -d hello
  - rmdir hello

notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
