#!/usr/bin/env bash

ppc_run ()
{
  name=$(id -un)
  sshpass -p "$name" ssh -t -oStrictHostKeyChecking=no 127.0.0.1 -p 22125 -l $name "$@"
}

if [ "$TARGET" == "powerpc-unknown-linux-gnu" ]
then
  cmd="cd /hostdir && $@"
  echo "Running: $cmd"
  ppc_run $cmd
elif [ "$TARGET" == "x86_64-pc-linux-gnu" ]
then
  docker exec -t $TARGET "$@"
elif [ "$TARGET" == "osx" ]
then
  eval "$@"
else
  echo "Unrecognized TARGET: $TARGET"
  exit 1
fi
