#!/usr/bin/env bash

ppc_run ()
{
  sshpass -p 'root' ssh -t -oStrictHostKeyChecking=no 127.0.0.1 -p 22125 -l root "$1"
}

if [ "$TARGET" == "powerpc-unknown-linux-gnu" ]
then
  ppc_run "cd /hostdir && $@"
elif [ "$TARGET" == "x86_64-pc-linux-gnu" ]
then
  docker exec -t $TARGET "$@"
elif [ "$TARGET" == "osx" ]
then
  eval "$@"
else
  echo "Unrecognized TARGET: $TARGET"
  exit 1
fi
